### ISSUE TITLE
WAF ACL does not show up in CloudFront

### ISSUE THREAD

**Issue by blair-anson** [aws-samples/aws-cloudfront-waf-ip-set#1]
I have run this as per the readme file, and it successully created a WAF ACL. However that WAF ACL is not visible in CloudFront when creating a new distribution. I think the WAF ACL (and related settings) need to be created in the `global` region, whereas this cdk uses the default user's default region (ie. `us-east-1`), however `global` is not a valid region for cdk so doing `export AWS_DEFAULT_REGION=global` before running `cdk bootstrap` does not work.
Perhaps there is another setting required in the cdk call to create the WAF ACL.

**Comment by carter3d** [comment]
Thank you for the feedback.  We will take a look and get back to you as soon as we can.

**Comment by carter3d** [comment]
OK, we've had a little time to research the issue.  The particular use case for this project is to attach a WAF Web ACL to an Application Load Balancer located in a region.  The Web ACL would have an IP Set rule attached to it, and that IP Set would be populated with the current CloudFront service endpoint CIDRs.  The goal here is to restrict traffic on the ALB to traffic coming from CloudFront only.  In this way, the WAF IP Set and Web ACL are both regional resources, as they are ultimately associated with an ALB running in the region.

**Comment by blair-anson** [comment]
Oh of course, the WAF ACL in Cloudfront is for traffic inbound to cloudfront. Where as controlling traffic from cloudfront to an internal resource would require an ALB to run the WAF ACL your tool creates. Apologies for the daft question.
